### ISSUE TITLE
Play command not working on iPad in Safari

### ISSUE THREAD

**Issue by kyleturman** [vimeo/player-api#6]
### REPRODUCE
1. Go to http://player.vimeo.com/playground on an iPad using Safari.
2. Press the "Play" button under "Simple Buttons".
### EXPECTED

Video will start playing using the .api('play') command.
### OBSERVED

The video looks like it's about to play, but never loads and transfers over to the iPad's HTML5 video player.

**Comment by Flimm** [comment]
I'm also experiencing this issue on Android, and getting this warning in the console:

>     player.js 10 Failed to execute 'requestFullScreen' on 'Element': API can only be initiated by a user gesture.

`play` should really fail gracefully here, it shouldn't leave the video in a state that makes it look like it's about to load to the user, with the pause button visible instead of the play button.

Unfortunately, there doesn't seem to be a known way to [feature detect if the browser supports playing a video without a user gesture](http://stackoverflow.com/q/32653510/247696), so writing a workaround to this is tricky.

**Comment by mirague** [comment]
+1
