### ISSUE TITLE
Ready fires before preview image has finished loading

### ISSUE THREAD

**Issue by jglover** [vimeo/player-api#92]
The preview image for a video in the player is still loading after the `ready` event has fired.
This only occurs on very slow connections (GPRS / < 50kb/s)

Steps to replicate:

- Throttle connection speed to GPRS / < 50kb/s

- Instantiate Froogaloop and call `addEvent('ready', () => { ... })`, add a breakpoint or console output to monitor when the event is fired/callback function is called.

The player and controls will appear on the page but the 'preview' image for the video will not yet be loaded e.g. `https://i.vimeocdn.com/video/xxxxxxxxx.webp?mw=xxxx&mh=xxxx&q=xx` will still be loading after `ready` fires.

**Comment by bdougherty** [comment]
This isn't really a bug. The `ready` event fires when the player is ready to receive and respond to api calls, not when everything has fully loaded. The controls wait for about 2 seconds for the thumbnail to load, otherwise they show anyway to avoid blocking the viewer for too long.

Also, I'd encourage you to update to use our new library: https://github.com/vimeo/player.js. There's a migration doc available too: https://github.com/vimeo/player.js/blob/master/docs/migrate-from-froogaloop.md

**Comment by jglover** [comment]
I figured as much, since the controls will still play the video it's not really an issue. Thanks.
